### ISSUE TITLE
Dependency of SS selection on I-DATA support

### ISSUE THREAD

**Issue by tuexen** [sctplab/sctp-idata#10]
Describe what happens when an application tries to select an stream scheduler requiring I-DATA support, but this isn't negotiated. `EINVAL` might the appropriate `errno`.
Describe what happens if the application selects a stream scheduler requiring I-DATA support before the association is established (on a listening socket, for example), and then the association is established without I-DATA support (since the peer doesn't support it).

This issue was brought up by Marcelo on the tsvwg mailing list.

**Comment by weinrank** [comment]
Shouldn't an SS always support non I-DATA mode?

**Comment by tuexen** [comment]
It doesn't make sense to use a stream scheduler **requiring** I-DATA, when I-DATA is not supported, does it?

**Comment by tuexen** [comment]
... Or have for a SS a defined behaviour when I-DATA is supported and when not. That would also be a possibility. What do you think?

**Comment by weinrank** [comment]
I meant b)
I choose an SS and when I-DATA is negotiated it runs in I-DATA mode - if supported by the SS.

**Comment by weinrank** [comment]
To be clear:
If the SS doesn't support interleaving, I-DATA-chunks should still be used but no message interleaving will happen.

**Comment by tuexen** [comment]
Fixed in https://github.com/sctplab/sctp-idata/commit/fe5bff65bf541353690b129dbff570b2ae272df2.
